---
dataset:
    # dataset
    ds:
        img_size: [96, 96]
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        p:
            dataset: 'camelyon'
            data_root: './data'
        q:
            dataset: 'camelyon'
            data_root: './data'
    # dataloader
    dl:
        batch_size: 64
        p:
            use_sampling: True
            sampling_by_variable: 'hospitals'
            sampling_weights: [1, 1, 1, 0, 1]
        q:
            use_sampling: True
            sampling_by_variable: 'hospitals'
            sampling_weights: [1, 1, 1, 1, 1]
        num_workers: 4
        pin_memory: True
